

---
apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
spec:
  nodeName: ip-192-168-48-204.ec2.internal
  containers:
  - name: backend-container
    image: nginx
    ports:
    - containerPort: 80


