

---
apiVersion: v1
kind: Pod
metadata:
  name: fbpod5
spec:
##  nodeName: ip-192-168-48-204.ec2.internal
  nodeSelector:
    env: prod
  containers:
  - name: fbpod
    image: nginx
    ports:
    - containerPort: 80


