

---
apiVersion: v1
kind: Pod
metadata:
  name: fbpod3
spec:
##  nodeName: ip-192-168-48-204.ec2.internal
  # nodeSelector:
  #   env: prod

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - prod
          
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1b

  containers:
  - name: fbpod
    image: nginx
    ports:
    - containerPort: 80


