  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: web
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: web
    template:
      metadata:
        labels:
          app: web
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - web
                  - prod 
              topologyKey: "kubernetes.io/hostname"
        containers:
        - name: nginx
          image: nginx